# This is a basic workflow to help you get started with Actions

name: CI PMD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
  

      - name: 'Installing SFDX scanner'
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: 'Run SFDX scanner'
       run: sfdx scanner:run --target /youtube-sfdx-delta-deploy-master/force-app/main/default --outfile results.html
