# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: 'Convert Metadata'
        run: sfdx force:source:convert --rootdir=force-app --outputdir=convert
      - name: 'Installing SFDX scanner'
        run: sfdx plugins:install @salesforce/sfdx-scanner
      - name: 'Run CD '
        run: cd  /force-app/main/
      - name: 'Run SFDX scanner'
        run: sfdx scanner:run --target default --outfile results.html
